### PR TITLE
WIP: Upgrade to Blender 2.8+

### PR DESCRIPTION
**Pull request by seedhartha**
I've begun upgrading the addon to Blender 2.8+.

Done:

- Class and module registration
- Import of geometry, animations and materials (diffuse and lightmap)

TODO:

- Import of walkmeshes and smoothing groups
- Export

@ndixUR, how'd you like this to be handled?

### CODE REVIEW

**Comment by ndixUR** [comment]
So, in general, there are two things I care about here:

1. Don't break compatibility w/ 2.79 unless there's a compelling reason to do so.
2. One of our *best-effort* goals with this code-base is maintaining *'similarity'* with Neverblender. By that I mean that we try to maximize the value our code can provide to Neverblender, and vice versa. So this means that the first approach whenever you work on this code is 'Has Neverblender done what I am trying to do, and, if so, I will pull in as much of that code as I can'.

Rule 1 trumps rule 2, and I should emphasize again the 'best-effort' part of rule 2 because Neverblender has not maintained 2.79 compatibility and changes non-functional code aspects more often than we track.

So, the ways I see these guiding principles pertaining to the current PR commit:

1. Change from register_module to register_class, great.
2. Change from scene.objects to scene.collections and bpy.data.lamps to bpy.data.lights: why not use feature detection to maintain backward compatibility? Example: light_coll = bpy.data.lights if hasattr(bpy.data, 'lights') else bpy.data.lamps
3. Changing all the attribute definitions from = to : (aka into type annotations), I'm less worried about Blender throwing warnings into the Python output than I am about annotations not being supported in 2.79's python 3.5*.
4. Rule 2 (and existing code) suggests some variable naming standards, like 'a_bmesh' should be 'bm'

Obviously this endeavor is made difficult in the relatively irresponsible ways that Python changes across versions, but there's no getting around that. If we hit a point where there are *required* changes that are incompatible, we can look at how to have branches for the two versions at that point...

Some other general bits I know of off the top of my head that might come up:
Don't use f"" strings, they are unsupported.
Don't use % for matrix multiplication.

**Comment by seedhartha** [comment]
I strongly disagree with trying to add 2.8 compatibility on top of 2.7 - these Blender versions are inherently incompatible with each other. Branching out sounds like the way to go. I was thinking more in lines of how are we going to branch out: separate repositories or separate folders in a single repository (possibly with a shared module in between)?

Also, I'm not a fan of certain parts of the NeverBlender code, e.g. its material setup when searching for similar materials. These parts I'd much rather rewrite than reuse.

**Comment by seedhartha** [comment]
All in all, it looks like I'm better off working in a separate repository, since we disagree on the two things of most importance to you 😅

**Comment by ndixUR** [comment]
Ahh, yeah, I'm not sure what makes you say that 2.79 and 2.8 are inherently incompatible. To me, 2.8 seems like a substantial but iterative change. Dropping Blender Internal is major, but Cycles exists in 2.79, so ¯\_(ツ)_/¯.

Also when I reverted the type annotations, the plugin continues to run fine in 2.92?

Also I definitely don't hesitate to abandon the techniques of Neverblender that don't make sense. The way it does armatures is quite different from how I've been implementing them, for example. I haven't seen how it does node-based material stuff, but I'm sure it is very different from what we need in Odyssey.

It sounds like you want to go your own way, so forking will probably be the way to go? In that case, I will look forward to seeing what a path to 2.8 support looks like.

**Comment by seedhartha** [comment]
Regarding type annotations: warnings aside, another problem is that old-style properties are not added to the UI, or at least that's what I'm experiencing in 2.91.

Regarding compatibility between 2.7 and 2.8: maybe "inherently incompatible" is a poor choice of words on my part. Still, from my point of view, there are enough differences between them to justfiy a code split. For example, material system is completely different, being node-based and all. Lights are different: there is no equivalent for Aurora light properties. UI has different icons and layout conventions (for one, 2.8 prefers single-column properties to multi-column, I think).

My point is that feature detection would complicate things unnecessarily, as you would now have to test the same code in both 2.7 and 2.8, not to mention the clutter it would add.

**Comment by seedhartha** [comment]
Let me know if you ever decide to relax the design requirements. In the mean time I'll be working on it in the forked repository. I really have no ambition beyond making a proper 2.8-compatible version of the plugin to aid reone development.

**Pull request closed without merging**
